### ISSUE TITLE
Inconsistency in default names?

### ISSUE THREAD

**Issue by kohenkatz** [mauricecalhoun/eloquent-otf#3]
Compare https://github.com/mauricecalhoun/eloquent-otf/blob/7bec29da85ca5e6cb380672d598e319bfb565402/app/Helpers.php#L9

```
$name = ($name) ?: 'onTheFly';
```
with https://github.com/mauricecalhoun/eloquent-otf/blob/7bec29da85ca5e6cb380672d598e319bfb565402/app/OTFServiceProvider.php#L13

```
$name = is_null($name) ? 'oft' : $name;
```

Is there a reason for the difference?

**Comment by mauricecalhoun** [comment]
No reason, it's fixed
